# Generated by Django 4.0.4 on 2022-04-26 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_account_branch_user_updated_at_transactions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='branch_id',
            new_name='branch',
        ),
    ]
