# Generated by Django 4.0.4 on 2022-04-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_account_account_type_alter_account_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('SAVING', 'Saving'), ('CURRENT', 'Current')], default='SAVING', max_length=300),
        ),
    ]
