# Generated by Django 4.0.4 on 2022-04-27 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_account_account_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': 'branches'},
        ),
    ]
