# Generated by Django 4.0.4 on 2022-04-27 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_branch_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-timestamp']},
        ),
    ]
