# Generated by Django 4.0.4 on 2022-04-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={},
        ),
    ]
