# Generated by Django 4.0.4 on 2022-04-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_account_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pin',
            field=models.CharField(default='', max_length=4),
        ),
    ]
